name: Apptainer Build and Deploy

on:
  workflow_call:
    inputs:
      apptainer_def:
        description: "Path to the Apptainer.def file"
        required: true
        type: string
      image_name:
        description: "Name of the .sif container to be produced"
        required: true
        type: string

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
      image: carlomt/apptainer:1.3.2
      options: --privileged

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set build tag
        id: set_vars
        run: |
          echo "tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lower=${repo_lower}" >> "$GITHUB_OUTPUT"

      - name: Build Container
        run: |
          apptainer build "${{ inputs.image_name }}" "${{ inputs.apptainer_def }}"

      - name: Login to GHCR
        # Usiamo il token automatico, non secrets.GHCR_PAT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_TOKEN" | apptainer registry login -u "${{ github.actor }}" --password-stdin oras://ghcr.io

      - name: Push Container to GHCR
        run: |
          IMAGE_URI="oras://ghcr.io/${{ steps.set_vars.outputs.repo_lower }}:${{ steps.set_vars.outputs.tag }}"
          echo "Pushing to: $IMAGE_URI"
          apptainer push "${{ inputs.image_name }}" "$IMAGE_URI"
