name: Test K8s Runner

on:
  workflow_dispatch:
  push:
    branches:
      - test-k8s-runner

jobs:
  test-pipeline:
    uses: ./.github/workflows/pipeline.yml
    permissions:
      contents: read
      packages: write
    with:
      image_name: "test.sif"
      apptainer_def: "Apptainer.def"